### ISSUE TITLE
[1.10.2] latest versions - unless pack contains Automated Redstone all recipes are missing

### ISSUE THREAD

**Issue by b0bst3r** [CD4017BE/CD4017BE_lib#10]
InductiveAutomation-1.10.2-5.3.4
CD4017BE_lib-1.10.2-4.4.3

Those 2 on their own without Automated Redstone and CD4017BE_lib has no items show up in JEI (except a warning item (triple ingot) that doesn't appear to be an actual item) which means all of Inductive Automation recipes are missing.

Add in Automated Redstone (AutomatedRedstone-1.10.2-4.4.1) and all the missing items from CD4017BE_lib re-appear and all the items in Inductive Automation are once again craftable.

Don't know if this is your intention or not but if it is then can you please clearly state this when downloading your mods.

**Comment by b0bst3r** [comment]
Error from Forge log which maybe related, and maybe not:- 

http://pastebin.ubuntu.com/24728427/

Actually it's not related since this forge log has automated redstone present lol

**Comment by CD4017BE** [comment]
Did you ...
1. install both mods + lib first and then remove AutomatedRedstone or
2. only install InductiveAutomation and the lib first and then add AutomatedRedstone ?

If 1. is the case you should be able to fix it by just deleting "config/cd4017be/compiled.dat"
Otherwise if 2. is the case then this is a bug, however maybe the above fix could still help.

Also please post all parts of the log that show a "ScriptException" including the followed stacktrace (when the recipes are actually not working)

**Comment by CD4017BE** [comment]
outdated, no further respond and probably solved, so lets close this last currently open issue.
