### ISSUE TITLE
[Question] 1.10.2 Ind Auto & Auto Redst

### ISSUE THREAD

**Issue by b0bst3r** [CD4017BE/CD4017BE_lib#7]
Are you planning on releasing a version of this lib that works with both Automated Redstone and Inductive Automation at the same time?

At the moment I get this with all 3 mods together - http://pastebin.ubuntu.com/23204351/

**Comment by CD4017BE** [comment]
I'm planning to do a rewrite of a few things in InductiveAutomation including mainly GUIs, better tool tips in GUIs, server to client synchronization for machines, using Forge capabilities, integrating the content of the experimental BTM builds and a few other things.
A lot of this already happened via the Lib which is the reason for the current incompatibility between them.

So the rewritten version of Automated Redstone can currently only be used on its own until I'm also done with the Inductive Automation rewrite.
There is a chance that you can install two different versions of the Lib at the same time (because the older one does not behave as a mod) but I think it won't work because of conflicts in the classes.
